version: '2'
services:
    # MYSQL_DATABASE、portsを追加
    db:
        build: ./db
        volumes:
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
        ports:
            - "3306:3306"
    web:
        build: ./web
        ports:
            - '10000:80'
        volumes:
            - ./html:/var/www/html
        depends_on:
            - db
        # stdin_open: true
        # tty: true